### ISSUE TITLE
启动空白页面，console里main.ts报错404

### ISSUE THREAD

**Issue by zhangyuanliang** [1720360649/ViteVue3Package#1]
<img width="1487" alt="image" src="https://github.com/1720360649/ViteVue3Package/assets/20222232/3f1c0c68-36ec-40f4-ba2e-b8244d78ba55">

**Comment by 1720360649** [comment]
这并不是项目基座的问题，请检查是否按照描述文件步骤操作，运行包测试时请先将需要测试的包先执行打包操作，然后在测试项目里安装和引入，包项目本身不可直接运行，必须需要打包后在测试项目中测试

**Comment by 1720360649** [comment]
> <img alt="image" width="1487" src="https://private-user-images.githubusercontent.com/20222232/299521083-3f1c0c68-36ec-40f4-ba2e-b8244d78ba55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODAyNTIsIm5iZiI6MTcwNjE3OTk1MiwicGF0aCI6Ii8yMDIyMjIzMi8yOTk1MjEwODMtM2YxYzBjNjgtMzZlYy00MGY0LWJhMmUtYjgyNDRkNzhiYTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEwNTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNzJlOGY0NWMyMzFmYzM4NzlhY2Q5NGYyZWI4NTU3NjgyNzBjNzc0NzI4OWM3NmFjYWEyMzMyYjIyZWMwZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XDOyiBp8zPkaNN7rYgfP-Azpy19KPtMv_wqYhojyji4">

感谢，但这并不是项目基座的问题，请检查你本身node环境是否适应vue3+vite且是否按照描述文件步骤操作，运行包测试时请先将需要测试的包先执行打包操作，然后在测试项目里安装和引入，包项目本身不可直接运行，必须需要打包后在测试项目中测试
